"""
EPC Module Constants

Defines all constant values used throughout the EPC module.
"""

# Typology Types
TYPOLOGY_ELECTROMECHANICAL = "Electromechanical"
TYPOLOGY_CIVIL = "Civil"
TYPOLOGY_STANDARD_SERVICE = "Standard/Service"

TYPOLOGY_CHOICES = [
    TYPOLOGY_ELECTROMECHANICAL,
    TYPOLOGY_CIVIL,
    TYPOLOGY_STANDARD_SERVICE
]

# Measurement Methods
MEASUREMENT_UNIT_BASED = "Unit-Based"
MEASUREMENT_PERCENTAGE_BASED = "Percentage-Based"
MEASUREMENT_MILESTONE_BASED = "Milestone-Based"

MEASUREMENT_CHOICES = [
    MEASUREMENT_UNIT_BASED,
    MEASUREMENT_PERCENTAGE_BASED,
    MEASUREMENT_MILESTONE_BASED
]

# Billing Tracks
BILLING_RA = "RA-Billing"
BILLING_MILESTONE = "Milestone-Billing"

BILLING_TRACKS = {
    TYPOLOGY_ELECTROMECHANICAL: BILLING_RA,
    TYPOLOGY_CIVIL: BILLING_RA,
    TYPOLOGY_STANDARD_SERVICE: BILLING_MILESTONE
}

# WBS Architectures
WBS_EQUIPMENT_BASED = "Equipment-Based"
WBS_PHASE_BASED = "Phase-Based"
WBS_MILESTONE_BASED = "Milestone-Based"

WBS_ARCHITECTURES = {
    TYPOLOGY_ELECTROMECHANICAL: WBS_EQUIPMENT_BASED,
    TYPOLOGY_CIVIL: WBS_PHASE_BASED,
    TYPOLOGY_STANDARD_SERVICE: WBS_MILESTONE_BASED
}

# Inventory Strategies
INVENTORY_SPATIAL_ZONE = "Spatial-Zone"
INVENTORY_BULK_WAREHOUSE = "Bulk-Warehouse"
INVENTORY_HIDDEN = "Hidden"

INVENTORY_STRATEGIES = {
    TYPOLOGY_ELECTROMECHANICAL: INVENTORY_SPATIAL_ZONE,
    TYPOLOGY_CIVIL: INVENTORY_BULK_WAREHOUSE,
    TYPOLOGY_STANDARD_SERVICE: INVENTORY_HIDDEN
}

# Default Values
DEFAULT_RETENTION_PERCENTAGE = 10
DEFAULT_ADVANCE_RECOVERY_THRESHOLD = 20
DEFAULT_ADVANCE_RECOVERY_CAP = 80

# Document Status
STATUS_DRAFT = "Draft"
STATUS_SUBMITTED = "Submitted"
STATUS_APPROVED = "Approved"
STATUS_REJECTED = "Rejected"
STATUS_ACTIVE = "Active"
STATUS_COMPLETED = "Completed"
STATUS_ON_HOLD = "On Hold"
STATUS_CANCELLED = "Cancelled"

# Regulatory Constants (Ethiopia)
ETHIOPIAN_VAT_RATE = 15  # Per Proclamation 1341/2024
ETHIOPIAN_PPA_2011 = "PPA 2011"

# ISO Standards
ISO_9001_2015 = "ISO 9001:2015"

# IS 456 Concrete Grades
CONCRETE_GRADES = [
    "M15", "M20", "M25", "M30", "M35", "M40", "M45", "M50", "M55", "M60"
]

# Exposure Conditions (IS 456)
EXPOSURE_MILD = "Mild"
EXPOSURE_MODERATE = "Moderate"
EXPOSURE_SEVERE = "Severe"
EXPOSURE_VERY_SEVERE = "Very Severe"
EXPOSURE_EXTREME = "Extreme"

EXPOSURE_CHOICES = [
    EXPOSURE_MILD,
    EXPOSURE_MODERATE,
    EXPOSURE_SEVERE,
    EXPOSURE_VERY_SEVERE,
    EXPOSURE_EXTREME
]